name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies (npm workspaces)
        run: npm ci

      - name: Build server and client
        run: npm run build

      - name: Upload client build artifact
        uses: actions/upload-artifact@v4
        with:
          name: client-dist
          path: client/dist

      - name: Upload server build artifact
        uses: actions/upload-artifact@v4
        with:
          name: server-dist
          path: server/dist
