name: Deploy Client to Vercel

on:
  push:
    branches: [ main, master ]
    paths:
      - 'client/**'
      - '.github/workflows/deploy-client-vercel.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Install deps (client)
        run: npm ci
        working-directory: client

      - name: Build (client)
        run: npm run build
        working-directory: client

      - name: Install Vercel CLI
        run: npm i -g vercel@latest

      - name: Deploy to Vercel (prod)
        run: vercel deploy --prebuilt --prod --cwd client --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
