name: Deploy Server to Render

on:
  push:
    branches: [ main, master ]
    paths:
      - 'server/**'
      - 'render.yaml'
      - '.github/workflows/deploy-server-render.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render deploy
        run: |
          curl -fsSL -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
        shell: bash
